### ISSUE TITLE
Hello author, I would like to ask about the visualization of the code pre-training model you provided

### ISSUE THREAD

**Issue by xiaodongqq** [feixue94/imp-release#1]
Dear author, after reading your code, I feel that your idea of this paper is very novel. I would like to ask how the pre-training models you provided can achieve visual matching results of corresponding images in the code. As shown in Figure 9 in your paper, the corresponding matching line results are shown.

**Comment by feixue94** [comment]
Hi, very sorry for the late reply. you can run the evaluation code and save the matching figuers at each iteration. if you have any problems, feel free to put them here

**Comment by xiaodongqq** [comment]
> Hi, very sorry for the late reply. you can run the evaluation code and save the matching figuers at each iteration. if you have any problems, feel free to put them here

Thank you very much for your answer！
