### ISSUE TITLE
Question about the command to extract local features and build correspondences for training

### ISSUE THREAD

**Issue by sapphireh** [feixue94/imp-release#11]
I follow the data preparation step to download the data you provide, and then try to extract local features as well as  build correspondences for training using the command:
`python3 -m dump.dump_megadepth --feature_type spp --base_path  path_of_megadepth  --save_path your_save_path`

however, there is an error shows that No such file or directory in the directory 'Megadepth/phoenix/...'. As your provided the data structure of Megadepth folder, the folder 'phoenix' is empty.
So, could you help me find out what mistake I made?
![image](https://github.com/feixue94/imp-release/assets/45328389/370f2593-5b8e-46de-8bcb-3d5932d48ca7)

**Comment by lizhi136** [comment]
How did you solve this？
