### ISSUE TITLE
Error of 'dump_megadepth.py'

### ISSUE THREAD

**Issue by Uchan1996** [feixue94/imp-release#5]
@feixue94 
Hi, author.
I found an error in the `'dump/dump_megadepth.py'`.
I ran the code which took about three days, and the code outputed the following error in the line 489.
`FileNotFoundError: [Errno 2] No such file or directory: 'asserts/mega_nvalid_spp.npy'`

I think `'asserts'` is a mistake of `'assets'`, right?
Also, what do the lines 486-489 of the code?
It seems that it just saves an empty dictionary.

**Comment by feixue94** [comment]
yes. you are right - it should be assets and is fixed. In 486-489,  we merge the number of valid pairs into a single file for random sampling in the training process

**Comment by Uchan1996** [comment]
Thank you for your quick fixing!
