### ISSUE TITLE
Question about "Undistorted_SfM"

### ISSUE THREAD

**Issue by Uchan1996** [feixue94/imp-release#6]
Hi, author.
I have a question about "Undistorted_SfM" data which you provide via Google Drive.
Is this a data D2-net originally provided, which is employed for LoFTR training?

LoFTR
> https://github.com/zju3dv/LoFTR/blob/master/docs/TRAINING.md

**Comment by feixue94** [comment]
it is provided by D2-Net (the original link provided by D2-Net is unavailable now). not very sure if LoFTER uses the same data.

**Comment by Uchan1996** [comment]
Thank you for your quick reply!
