### ISSUE TITLE
Train with my own dataset

### ISSUE THREAD

**Issue by Strollercarra** [feixue94/imp-release#8]
Dear author, thanks a lot for your released codes. I am wondering that how to train with my own dataset in the codes. Would you mind giving me some instances in your codes? Looking forward to your early reply.

**Comment by feixue94** [comment]
Hi, 
Only keypoints (descriptors, scores, coordinates) and gt-matches of image pairs are needed for training. If you want to train the imp on your own dataset, you can follow the code in dump/dump_megadepth.py to  build your own training samples and use the training script to start the training.

**Comment by feixue94** [comment]
This issue is closed. If you have any other questions, feel free to reopen it.
